### PR TITLE
Add beginnings of testing for messaging

### PR DESCRIPTION
**Pull request by radar**

### CODE REVIEW

**Comment by bjeanes** [comment]
Do you wanna try whipping up a travis yml too? Might as well get this thing ticking :)

**Comment by radar** [comment]
#5 should be merged before this, otherwise the tests will fail _dramatically_.

**Comment by bjeanes** [comment]
I'm seeing some weird git history things here. Not sure if intentional: 

2014-07-22 at 5 27 pm

It may be a weird GH thing because of the shared commits, so I'll check with CLI when I get home but I definitely wouldn't expect to see your `snoop` move commit in here.

**Comment by radar** [comment]
Let me check it out.

**Comment by radar** [comment]
Tidier now. Git is hard.

**Comment by bjeanes** [comment]
Looks good. One thing I was planning to start adding tests for tonight is some of the failure modes like mismatched sizes or unknown message types etc. Will do that soon I think.

**Comment by bjeanes** [comment]
Git history still looks a bit messed up. It includes bf97d95b364338c3bca333570d71554ee3767b74 which looks like a rebased version of 319eb16, which is already in master.

**Comment by bjeanes** [comment]
FYI I'm going to cherry pick some of what you have in here already because it'll be useful to me atm. Rebase from my master when you get a chance! :)

**Comment by radar** [comment]
I've rebased and force pushed now. I think that's the last couple of tests that I'll write for now.

Next job: making the client talk to the bulb.

**Comment by bjeanes** [comment]
> Next job: making the client talk to the bulb.

Cool. I think @aussiegeek and @wolfeidau were wanting a Go lib. Maybe they have input (in a different issue or discussion, that is) on what that client could/should/would look like. Also @jlsuttles wanted to play around with it and possibly help out so she may also have input too.

**Comment by wolfeidau** [comment]
Yes, happy to help out.

I was going to start pulling it apart today but it looks like @radar started on it already!

Will pull the repo down and take a look around.

**Pull request merged**
